Repository Danil-Alr/SpaceDream_ADT, pull requests merged in 2025-06, with the labels that each got.

#91 добытчик ТК
  Content.Server/ItemMiner/Components/TelecrystalMinerComponent.cs
  Content.Server/ItemMiner/Systems/ItemMinerSystem.cs
  Content.Server/ItemMiner/Systems/TelecrystalMinerSystem.cs
  Content.Shared/ItemMiner/ItemMinerComponent.cs
  Content.Shared/ItemMiner/ItemMinerEvents.cs
  Resources/Locale/en-US/_Goobstation/store/uplink-catalog.ftl
  Resources/Locale/en-US/_Goobstation/tcminer/tc-miner.ftl
  Resources/Locale/ru-RU/_Goobstation/store/uplink-catalog.ftl
  Resources/Locale/ru-RU/_Goobstation/tcminer/tc-miner.ftl
  Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
  Resources/Prototypes/_Goobstation/Catalog/uplink_catalog.yml
  Resources/Prototypes/_Goobstation/Entities/Structures/Machines/tcprinter.yml
  Resources/Prototypes/_Goobstation/tags.yml
  Resources/Textures/_Goobstation/Structures/Machines/tc_printer.rsi/display.png
  Resources/Textures/_Goobstation/Structures/Machines/tc_printer.rsi/icon.png
  Resources/Textures/_Goobstation/Structures/Machines/tc_printer.rsi/meta.json
  Resources/Textures/_Goobstation/Structures/Machines/tc_printer.rsi/printing.png
  Resources/Textures/_Goobstation/Structures/Machines/tc_printer.rsi/unshaded.png
Labels: S: Untriaged, Changes: Sprites, Changes: Localization

#98 [ADD] Делаю вещи
  Resources/Locale/ru-RU/SD/clothing.ftl
  Resources/Locale/ru-RU/SD/toys.ftl
  Resources/Prototypes/ADT/Loadouts/Jobs/Civilian/janitor.yml
  Resources/Prototypes/Loadouts/Jobs/Civilian/janitor.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/Loadouts/role_loadouts.yml
  Resources/Prototypes/SD/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/SD/Entities/Clothing/Shoes/boots.yml
  Resources/Prototypes/SD/Entities/Objects/Fun/toys.yml
  Resources/Textures/SD/Clothing/Belt/tacticalmaid.rsi/equipped-BELT.png
  Resources/Textures/SD/Clothing/Belt/tacticalmaid.rsi/icon.png
  Resources/Textures/SD/Clothing/Belt/tacticalmaid.rsi/inhand-left.png
  Resources/Textures/SD/Clothing/Belt/tacticalmaid.rsi/inhand-right.png
  Resources/Textures/SD/Clothing/Belt/tacticalmaid.rsi/meta.json
  Resources/Textures/SD/Clothing/Shoes/tacticalmaid.rsi/equipped-FEET.png
  Resources/Textures/SD/Clothing/Shoes/tacticalmaid.rsi/icon.png
  Resources/Textures/SD/Clothing/Shoes/tacticalmaid.rsi/inhand-left.png
  Resources/Textures/SD/Clothing/Shoes/tacticalmaid.rsi/inhand-right.png
  Resources/Textures/SD/Clothing/Shoes/tacticalmaid.rsi/meta.json
  Resources/Textures/SD/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/SD/Objects/Fun/toys.rsi/plush_ZHETS.png
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: Localization, Changes: No C#

#103 ElfFix
  Resources/Locale/ru-RU/SD/aegi.ftl
  Resources/Locale/ru-RU/SD/aegi_names.ftl
  Resources/Prototypes/ADT/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/ADT/Loadouts/Miscellaneous/underwear.yml
  Resources/Prototypes/Entities/Mobs/Player/humanoid.yml
  Resources/Prototypes/Loadouts/Miscellaneous/survival.yml
  Resources/Prototypes/SD/Body/Organs/aegi.yml
  Resources/Prototypes/SD/Damage/modifier_sets.yml
  Resources/Prototypes/SD/Datasets/Names/aegi_first_female.yml
  Resources/Prototypes/SD/Datasets/Names/aegi_first_male.yml
  Resources/Prototypes/SD/Datasets/Names/aegi_last.yml
  Resources/Prototypes/SD/Entities/Mobs/Species/aegi.yml
  Resources/Prototypes/SD/Species/aegi.yml
Labels: size/M, Changes: Localization, Changes: No C#

#106 Понижение доступа у сервисного работника
  Resources/Prototypes/Roles/Jobs/Civilian/service_worker.yml
Labels: size/XS, Changes: No C#

#107 more expensive harvaster
  Resources/Prototypes/ADT/Entities/Objects/Devices/Circuitboards/Machine/production.yml
  Resources/Prototypes/ADT/Research/experimental.yml
Labels: size/S, Changes: No C#

#114 Upstream v1.6.1
  Content.Server/ADT/Supermatter/Systems/SupermatterAnnounceSystem.cs
  Content.Server/ADT/Supermatter/Systems/SupermatterProcessingSystem.cs
  Content.Server/ADT/Supermatter/Systems/SupermatterSystem.cs
  Content.Server/Radiation/Systems/RadiationSystem.GridCast.cs
  Content.Shared/ADT/Supermatter/Components/SupermatterComponent.cs
  Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Head/hats.ftl
  Resources/Prototypes/ADT/Catalog/VendingMachines/Inventories/prazatclothing.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/hats.yml
  Resources/Prototypes/ADT/Entities/Mobs/NPCs/hallucinations.yml
  Resources/Prototypes/ADT/Entities/Objects/Misc/SupermatterKudzu.yml
  Resources/Prototypes/Entities/Structures/Walls/walls.yml
  Resources/Prototypes/Entities/Structures/Windows/plasma.yml
  Resources/Prototypes/Entities/Structures/Windows/rplasma.yml
  Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
  Resources/Prototypes/Entities/Structures/Windows/uranium.yml
  Resources/Textures/ADT/Clothing/Head/Hats/drink_cap.rsi/equipped-HELMET.png
  Resources/Textures/ADT/Clothing/Head/Hats/drink_cap.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Hats/drink_cap.rsi/meta.json
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: Localization
