Repository Danil-Alr/SpaceDream_ADT, pull requests merged in 2025-05, with the labels that each got.

#47 Респрайт белья ОСЩ (Real AND True) (а ещё фикс говна)
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/Weaponry/projectiles.yml
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/Weaponry/rockets.yml
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/combat.yml
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/controls.yml
  Resources/Prototypes/Species/moth.yml
  Resources/Textures/ADT/Clothing/Underwear/Bottom/blueshield_panties.rsi/equipped-UNDERWEARB.png
  Resources/Textures/ADT/Clothing/Underwear/Bottom/blueshield_panties.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/Bottom/blueshield_panties.rsi/meta.json
  Resources/Textures/ADT/Clothing/Underwear/Top/blueshield_bra.rsi/equipped-UNDERWEART.png
  Resources/Textures/ADT/Clothing/Underwear/Top/blueshield_bra.rsi/icon.png
  Resources/Textures/ADT/Clothing/Underwear/Top/blueshield_bra.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Medical/brigmedhypo.rsi/inhand-right.png
  Resources/Textures/SD/Objects/Specific/Medical/bshypo.rsi/inhand-right.png
  Resources/Textures/SD/Objects/Weapons/UAVs/Projectiles/switchblade.rsi/emp.png
  Resources/Textures/SD/Objects/Weapons/UAVs/Projectiles/switchblade.rsi/he.png
  Resources/Textures/SD/Objects/Weapons/UAVs/Projectiles/switchblade.rsi/meta.json
  Resources/Textures/SD/Objects/Weapons/UAVs/saksaul.rsi/icon.png
  Resources/Textures/SD/Objects/Weapons/UAVs/saksaul.rsi/meta.json
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: No C#

#51 Нормальный фонарик у ПДА + Новая музыка в джукбоксах
  Resources/Audio/Jukebox/attributions.yml
  Resources/Audio/SD/Jukebox/Afroman-Because-I-Got-High.ogg
  Resources/Audio/SD/Jukebox/BLACK-SABBATH.ogg
  Resources/Audio/SD/Jukebox/Blizzard.ogg
  Resources/Audio/SD/Jukebox/Caramelldansen.ogg
  Resources/Audio/SD/Jukebox/Fine.ogg
  Resources/Audio/SD/Jukebox/Gorilla-Feel-Good-Inc.ogg
  Resources/Audio/SD/Jukebox/Hotline-Miami-2-Frantic-Aerobics.ogg
  Resources/Audio/SD/Jukebox/Hotline-Miami-2-Run.ogg
  Resources/Audio/SD/Jukebox/Kavinsky-Nightcall.ogg
  Resources/Audio/SD/Jukebox/Michael-Jackson-Billie-Jean.ogg
  Resources/Audio/SD/Jukebox/Nirvana-Come-As-You-Are.ogg
  Resources/Audio/SD/Jukebox/Nirvana-Smells-Like-Teen-Spirit.ogg
  Resources/Audio/SD/Jukebox/Overdose.ogg
  Resources/Audio/SD/Jukebox/Paint-It-Black.ogg
  Resources/Audio/SD/Jukebox/Pixies-Where-Is-My-Mind.ogg
  Resources/Audio/SD/Jukebox/Surf-Curse-Disco.ogg
  Resources/Audio/SD/Jukebox/Surf-Curse-Freaks.ogg
  Resources/Audio/SD/Jukebox/attributions.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/SD/Catalog/Jukebox/Standart.yml
Labels: S: Untriaged, size/M, Changes: Audio, Changes: No C#

#60 Патч фауны лаваленда + небольшой твик ядра легиона
  Content.Shared/Fluids/SharedPuddleSystem.Evaporation.cs
  Resources/Prototypes/ADT/Entities/Mobs/NPCs/lavaland.yml
  Resources/Prototypes/Entities/Mobs/NPCs/asteroid.yml
  Resources/Prototypes/Entities/Mobs/NPCs/lavaland.yml
  Resources/Prototypes/Entities/Objects/Specific/Lavaland/MobLoot.yml
  Resources/Prototypes/SD/Reagents/biological.yml
Labels: size/S, S: Untriaged

#61 Танки БРИТАЯ РАКУШКА
  Resources/Audio/ADT/Mecha/tank.ogg
  Resources/Prototypes/SD/Entities/Objects/Fun/tank.yml
  Resources/Textures/Objects/Specific/Mech/tank.rsi/meta.json
  Resources/Textures/Objects/Specific/Mech/tank.rsi/t34tank-broken.png
  Resources/Textures/Objects/Specific/Mech/tank.rsi/t34tank-open.png
  Resources/Textures/Objects/Specific/Mech/tank.rsi/t34tank.png
  Resources/Textures/Objects/Specific/Mech/tank.rsi/tigertank-broken.png
  Resources/Textures/Objects/Specific/Mech/tank.rsi/tigertank-open.png
  Resources/Textures/Objects/Specific/Mech/tank.rsi/tigertank.png
  Resources/Textures/Objects/Specific/Mech/tank.rsi/vattank-open.png
  Resources/Textures/Objects/Specific/Mech/tank.rsi/vattank.png
Labels: S: Untriaged, size/XS, size/M, Changes: Sprites, Changes: Audio, Changes: No C#

#58 Сумка Биба
  Resources/Locale/ru-RU/SD/satchel.ftl
  Resources/Prototypes/SD/Entities/Clothing/Back/satchel.yml
Labels: size/S, S: Untriaged, Changes: Localization, Changes: No C#

#48 добавление пилота на некоторые станции и фикс обреза, добавление плюшевой игрушки РК-22
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_aspid.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_bagel.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_box.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_delta.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_fland.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_kerberos.yml
  Resources/Prototypes/Recipes/Construction/Graphs/weapons/shotgunsawn.yml
  Resources/Prototypes/SD/Entities/Objects/Fun/toys.yml
  Resources/Textures/SD/Objects/Fun/toys.rsi/meta.json
  Resources/Textures/SD/Objects/Fun/toys.rsi/rk22_plush.png
Labels: size/S, S: Untriaged, Changes: Sprites, Changes: No C#

#63 Добавление бутылок кваса в АлкоМат
  Resources/Prototypes/Catalog/VendingMachines/Inventories/boozeomat.yml
  Resources/Prototypes/Entities/Markers/Spawners/Random/Food_Drinks/drinks_bottles.yml
  Resources/Prototypes/Entities/Objects/Consumable/Drinks/drinks_bottles.yml
  Resources/Textures/Objects/Consumable/Drinks/kvasbottle.rsi/icon.png
  Resources/Textures/Objects/Consumable/Drinks/kvasbottle.rsi/meta.json
Labels: size/S, S: Untriaged, Changes: Sprites, Changes: No C#

#69 Search placeholder in jukebox
  Content.Client/Audio/Jukebox/JukeboxMenu.xaml
  Content.Client/Audio/Jukebox/JukeboxMenu.xaml.cs
  Resources/Locale/en-US/jukebox/jukebox-menu.ftl
  Resources/Locale/ru-RU/jukebox/jukebox-menu.ftl
Labels: size/S, S: Untriaged, Changes: UI, Changes: Localization

#72 Контрактник
  Resources/Audio/ADT/Entities/Objects/Weapons/Melee/contractorbatonhit.ogg
  Resources/Audio/ADT/Mecha/nominalV1.ogg
  Resources/Audio/ADT/Mecha/nominal_contract.ogg
  Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Back/mods.ftl
  Resources/Locale/ru-RU/ADT/prototypes/Entities/Objects/Weapons/Melee/melee.ftl
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/syndicate.ftl
  Resources/Locale/ru-RU/store/categories.ftl
  Resources/Prototypes/ADT/Catalog/uplink_catalog.yml
  Resources/Prototypes/ADT/Entities/Clothing/Back/mods.yml
  Resources/Prototypes/ADT/Entities/Clothing/Hands/modsuit_gloves.yml
  Resources/Prototypes/ADT/Entities/Clothing/Head/modsuit-helmets.yml
  Resources/Prototypes/ADT/Entities/Clothing/OuterClothing/modsuits.yml
  Resources/Prototypes/ADT/Entities/Clothing/Shoes/modsuit_boots.yml
  Resources/Prototypes/ADT/Entities/Objects/Weapons/Melee/contractor_baton.yml
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/Entities/Objects/Specific/syndicate.yml
  Resources/Prototypes/Roles/Antags/traitor.yml
  Resources/Prototypes/Store/categories.yml
  Resources/Prototypes/Store/presets.yml
  Resources/Textures/ADT/Clothing/Back/Modsuit/syndicate_contractor.rsi/equipped-BACKPACK.png
  Resources/Textures/ADT/Clothing/Back/Modsuit/syndicate_contractor.rsi/icon.png
  Resources/Textures/ADT/Clothing/Back/Modsuit/syndicate_contractor.rsi/inhand-left.png
  Resources/Textures/ADT/Clothing/Back/Modsuit/syndicate_contractor.rsi/inhand-right.png
  Resources/Textures/ADT/Clothing/Back/Modsuit/syndicate_contractor.rsi/meta.json
  Resources/Textures/ADT/Clothing/Hands/Modsuit/syndicate_contractor.rsi/equipped-HAND.png
  Resources/Textures/ADT/Clothing/Hands/Modsuit/syndicate_contractor.rsi/icon.png
  Resources/Textures/ADT/Clothing/Hands/Modsuit/syndicate_contractor.rsi/meta.json
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/equipped-head-light.png
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/equipped-head-unshaded.png
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/equipped-head.png
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/icon-flash.png
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/icon-unshaded.png
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/icon.png
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/light-overlay.png
  Resources/Textures/ADT/Clothing/Head/Modsuit/syndicate_contractor.rsi/meta.json
  Resources/Textures/ADT/Clothing/OuterClothing/Modsuit/syndicate_contractor.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/ADT/Clothing/OuterClothing/Modsuit/syndicate_contractor.rsi/icon.png
  Resources/Textures/ADT/Clothing/OuterClothing/Modsuit/syndicate_contractor.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Modsuit/syndicate_contractor.rsi/equipped-FEET.png
  Resources/Textures/ADT/Clothing/Shoes/Modsuit/syndicate_contractor.rsi/icon-on.png
  Resources/Textures/ADT/Clothing/Shoes/Modsuit/syndicate_contractor.rsi/icon.png
  Resources/Textures/ADT/Clothing/Shoes/Modsuit/syndicate_contractor.rsi/meta.json
  Resources/Textures/ADT/Clothing/Shoes/Modsuit/syndicate_contractor.rsi/on-equipped-FEET.png
  Resources/Textures/ADT/Objects/Weapons/Melee/contractor_baton.rsi/contractor_off.png
  Resources/Textures/ADT/Objects/Weapons/Melee/contractor_baton.rsi/contractor_on.png
  Resources/Textures/ADT/Objects/Weapons/Melee/contractor_baton.rsi/meta.json
  Resources/Textures/ADT/Objects/Weapons/Melee/contractor_baton.rsi/off-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/contractor_baton.rsi/off-inhand-right.png
  Resources/Textures/ADT/Objects/Weapons/Melee/contractor_baton.rsi/on-inhand-left.png
  Resources/Textures/ADT/Objects/Weapons/Melee/contractor_baton.rsi/on-inhand-right.png
  Resources/Textures/Objects/Devices/communication.rsi/meta.json
  Resources/Textures/Objects/Devices/communication.rsi/svo.png
Labels: size/M, Changes: Sprites, Changes: Audio, Changes: Localization, Changes: No C#

#73 Lavaland: Модуль Бладдранкера
  Content.Shared/ADT/Fauna/Components/FaunaComponent.cs
  Content.Shared/ADT/Weapons/Ranged/Upgrades/Components/GunUpgradeBloodDrunkerComponent.cs
  Content.Shared/ADT/Weapons/Ranged/Upgrades/Components/GunUpgradeReagentAddComponent.cs
  Content.Shared/ADT/Weapons/Ranged/Upgrades/GunUpgradeSystem.cs
  Content.Shared/SD/ERPStatus.cs/EnumERPStatus.cs
  Content.Shared/SD/HunterEye/HunterEyeDamageReductionComponent.cs
  Content.Shared/SD/HunterEye/HunterEyeDamageReductionSystem.cs
  Resources/Locale/ru-RU/SD/blooddrunker.ftl
  Resources/Prototypes/ADT/Entities/Mobs/NPCs/Megafauna/BloodMiner.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Salvage/lavaland_loot.yml
  Resources/Prototypes/SD/Alerts/alerts.yml
  Resources/Prototypes/SD/Reagents/medicine.yml
  Resources/Prototypes/SD/status_effects.yml
  Resources/Textures/SD/Objects/Specific/Salvage/Artefacts/hunter_eye.rsi/hunter-eye.png
  Resources/Textures/SD/Objects/Specific/Salvage/Artefacts/hunter_eye.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Salvage/Artefacts/tail_spike.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Salvage/Artefacts/tail_spike.rsi/tail-spike.png
Labels: size/M, Changes: Sprites, Changes: Localization

#52 Добавление старой дриповой курточки вардену
  Resources/Prototypes/Loadouts/Jobs/Security/warden.yml
  Resources/Prototypes/Loadouts/loadout_groups.yml
  Resources/Prototypes/SD/Entities/Clothing/OuterClothing/wintercoats.yml
  Resources/Textures/SD/Clothing/OuterClothing/WinterCoats/coatwardenarmored.rsi/equipped-OUTERCLOTHING-resomi.png
  Resources/Textures/SD/Clothing/OuterClothing/WinterCoats/coatwardenarmored.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/SD/Clothing/OuterClothing/WinterCoats/coatwardenarmored.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/SD/Clothing/OuterClothing/WinterCoats/coatwardenarmored.rsi/icon.png
  Resources/Textures/SD/Clothing/OuterClothing/WinterCoats/coatwardenarmored.rsi/inhand-left.png
  Resources/Textures/SD/Clothing/OuterClothing/WinterCoats/coatwardenarmored.rsi/inhand-right.png
  Resources/Textures/SD/Clothing/OuterClothing/WinterCoats/coatwardenarmored.rsi/meta.json
Labels: size/S, S: Untriaged, Changes: Sprites, Changes: No C#

#74 Upstream v1.4
  Content.Client/ADT/Lobby/UI/DiscordLinkWindow.xaml.cs
  Content.Shared/CCVar/CCVars.Game.Infolinks.cs
  README.md
  Resources/Locale/ru-RU/ADT/prototypes/Entities/Clothing/Belt/belts.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/ADT/tags.yml
  Resources/Prototypes/Catalog/Fills/Crates/service.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/curadrobe.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/lawdrobe.yml
  Resources/Prototypes/Entities/Mobs/Player/silicon.yml
  Resources/Prototypes/Entities/Objects/Misc/rubber_stamp.yml
  Resources/Textures/ADT/Clothing/Belt/folder_belt.rsi/equipped-BELT.png
  Resources/Textures/ADT/Clothing/Belt/folder_belt.rsi/icon.png
  Resources/Textures/ADT/Clothing/Belt/folder_belt.rsi/meta.json
Labels: size/S, S: Untriaged, Changes: Sprites, Changes: UI, Changes: Localization

#75 [FIX] search placeholder in jukebox
  Content.Client/Audio/Jukebox/JukeboxMenu.xaml.cs
Labels: size/S, S: Untriaged, Changes: UI
