Repository Danil-Alr/SpaceDream_ADT, pull requests merged in 2025-04, with the labels that each got.

#8 Обнова v 1.0.1
  Content.Client/Materials/UI/MaterialDisplay.xaml.cs
  Content.Server/ADT/Chemistry/RandomPillSystem.cs
  Content.Shared/CCVar/CCVars.Game.cs
  Content.Shared/Chemistry/Components/PillComponent.cs
  Resources/Changelog/1ChangelogADT.yml
  Resources/Locale/ru-RU/ADT/personalization.ftl
  Resources/Locale/ru-RU/ADT/prototypes/Entities/Mobs/Customization/Markings/demon_hair.ftl
  Resources/Prototypes/ADT/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/ADT/Entities/Mobs/Customization/Markings/demon_hair.yml
  Resources/Prototypes/ADT/Entities/Personalization/Clothing/personalization_clothing.yml
  Resources/Prototypes/ADT/Entities/Personalization/Objects/personalization_items.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_aspid.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_avrite.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_bagel.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_box.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_cluster.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_cluster_legacy.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_delta.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_fland.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_gemini.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_kerberos.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_marathon.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_meta.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_packed.yml
  Resources/Prototypes/ADT/Maps/ADTMaps/adt_saltern.yml
  Resources/Prototypes/ADT/Parallaxes/ocean.yml
  Resources/Prototypes/Entities/Clothing/Belt/belts.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/randompill.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/Entities/Structures/Windows/clockwork.yml
  Resources/Prototypes/Entities/Structures/Windows/ruranium.yml
  Resources/Textures/ADT/Clothing/Neck/Cloaks/diamond_cape.rsi/equipped-NECK.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-bubble_gum.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-gorgona.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-gorgona_2.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-morning_hairstyle.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-morning_hairstyle_2.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-morning_hairstyle_3.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-ponytail.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-shaved_female.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-shaved_unisex.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-valkyrie_scythe.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-valkyrie_scythe_2.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/hair-valkyrie_scythe_3.png
  Resources/Textures/ADT/Mobs/Customization/Human/custom.rsi/meta.json
  Resources/Textures/ADT/Parallaxes/attributions.yml
  Resources/Textures/ADT/Parallaxes/land.png
  Resources/Textures/ADT/Personalization/toys.rsi/meta.json
  Resources/Textures/ADT/Personalization/toys.rsi/plushie_anagiri.png
Labels: S: Untriaged, size/M

#12 [FIX] Показ ERP статуса теперь не зависит от наличия описания
  Content.Server/Station/Systems/StationSpawningSystem.cs
Labels: size/S

#11 Гипоспрей ОСЩ и Бригмедика
  Resources/Locale/ru-RU/ss14-ru/prototypes/entities/objects/specific/medical/hypospray.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Lockers/centcomm.yml
  Resources/Prototypes/ADT/Catalog/Fills/Lockers/security.yml
  Resources/Prototypes/Entities/Objects/Specific/Medical/hypospray.yml
  Resources/Textures/SD/Objects/Specific/Medical/brigmedhypo.rsi/equipped-BELT.png
  Resources/Textures/SD/Objects/Specific/Medical/brigmedhypo.rsi/hypo.png
  Resources/Textures/SD/Objects/Specific/Medical/brigmedhypo.rsi/inhand-left.png
  Resources/Textures/SD/Objects/Specific/Medical/brigmedhypo.rsi/inhand-right.png
  Resources/Textures/SD/Objects/Specific/Medical/brigmedhypo.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Medical/bshypo.rsi/equipped-BELT.png
  Resources/Textures/SD/Objects/Specific/Medical/bshypo.rsi/hypo.png
  Resources/Textures/SD/Objects/Specific/Medical/bshypo.rsi/inhand-left.png
  Resources/Textures/SD/Objects/Specific/Medical/bshypo.rsi/inhand-right.png
  Resources/Textures/SD/Objects/Specific/Medical/bshypo.rsi/meta.json
Labels: S: Untriaged, size/M

#13 Дзета и Сигма [EVENTS]
  Resources/Locale/ru-RU/ADT/alert-levels/alert-levels.ftl
Labels: size/S, S: Untriaged

#15 remove cadet req
  Resources/Prototypes/Roles/Jobs/Security/security_cadet.yml
Labels: S: Untriaged, size/XS

#20 cqc for shield
  Resources/Prototypes/ADT/Roles/Jobs/Command/blueshieldofficer.yml
Labels: size/S, S: Untriaged

#19 Отражающий бронежилет Синдиката
  Resources/Locale/ru-RU/SD/armor.ftl
  Resources/Locale/ru-RU/SD/uplink.ftl
  Resources/Prototypes/Catalog/uplink_catalog.yml
  Resources/Prototypes/SD/Catalog/uplink_catalog.yml
  Resources/Prototypes/SD/Entities/Clothing/OuterClothing/Armor/vests.yml
  Resources/Textures/SD/Entities/Clothing/OuterClothing/Armor/syndreflect.rsi/equipped-OUTERCLOTHING-vox.png
  Resources/Textures/SD/Entities/Clothing/OuterClothing/Armor/syndreflect.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/SD/Entities/Clothing/OuterClothing/Armor/syndreflect.rsi/icon.png
  Resources/Textures/SD/Entities/Clothing/OuterClothing/Armor/syndreflect.rsi/inhand-left.png
  Resources/Textures/SD/Entities/Clothing/OuterClothing/Armor/syndreflect.rsi/inhand-right.png
  Resources/Textures/SD/Entities/Clothing/OuterClothing/Armor/syndreflect.rsi/meta.json
Labels: size/S, S: Untriaged

#18 mothfix
  Content.Server/Speech/EntitySystems/MothAccentSystem.cs
Labels: size/S, S: Untriaged

#21 AntiGhost
  Content.Client/Chat/Managers/ChatManager.cs
  Content.Client/Chat/UI/SpeechBubble.cs
  Content.Client/Input/ContentContexts.cs
  Content.Client/Options/UI/Tabs/KeyRebindTab.xaml.cs
  Content.Client/UserInterface/Systems/Chat/ChatUIController.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelFilterPopup.xaml.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorButton.cs
  Content.Client/UserInterface/Systems/Chat/Controls/ChannelSelectorPopup.cs
  Content.Client/UserInterface/Systems/Chat/Widgets/ChatBox.xaml.cs
  Content.Client/VendingMachines/UI/VendingMachineMenu.xaml.cs
  Content.Server/ADT/Language/LanguageTypes/Emotes.cs
  Content.Server/Chat/Commands/MeCommand.cs
  Content.Server/Chat/Managers/ChatManager.cs
  Content.Server/Chat/Managers/IChatManager.cs
  Content.Server/Chat/Systems/ChatSystem.cs
  Content.Server/Chat/V2/Messages.cs
  Content.Shared/Chat/ChatChannel.cs
  Content.Shared/Chat/ChatSelectChannel.cs
  Content.Shared/Chat/SharedChatSystem.cs
  Content.Shared/Chat/V2/Types.cs
  Content.Shared/Input/ContentKeyFunctions.cs
  Resources/Locale/ru-RU/ADT/collectivemind/options-menu.ftl
  Resources/Locale/ru-RU/chat/ui/chat-box.ftl
  Resources/ServerInfo/Guidebook/Engineering/Airlocks.xml
  Resources/keybinds.yml
Labels: S: Untriaged, size/M

#23 Spycrabbran
  Resources/Prototypes/Entities/Clothing/OuterClothing/hardsuits.yml
  Resources/Prototypes/SD/Catalog/Cargo/cargo_shuttle.yml
Labels: size/S, S: Untriaged

#29 AntiGhost command
  Content.Server/SD/Chat/Commands/AntiGhostCommand.cs
Labels: size/S, S: Untriaged

#26 [BUG] re-add shield's unability to shoot
  Resources/Prototypes/ADT/Roles/Jobs/Command/blueshieldofficer.yml
Labels: S: Untriaged, size/XS

#27 Максимальная длинна флавора
  Content.Shared/Preferences/HumanoidCharacterProfile.cs
Labels: S: Untriaged, size/XS

#35 Волосы для молей
  Resources/Prototypes/Species/moth.yml
Labels: S: Untriaged, size/XS

#32 Ударный БПЛА Саксуал с заделом на будущее развитие темы
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/Weaponry/projectiles.yml
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/Weaponry/rockets.yml
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/combat.yml
  Resources/Prototypes/SD/Entities/Objects/Weapons/UAVs/controls.yml
  Resources/Prototypes/tags.yml
  Resources/Textures/SD/Objects/Weapons/UAVs/Projectiles/switchblade.rsi/emp.png
  Resources/Textures/SD/Objects/Weapons/UAVs/Projectiles/switchblade.rsi/he.png
  Resources/Textures/SD/Objects/Weapons/UAVs/Projectiles/switchblade.rsi/meta.json
  Resources/Textures/SD/Objects/Weapons/UAVs/saksaul.rsi/icon.png
  Resources/Textures/SD/Objects/Weapons/UAVs/saksaul.rsi/meta.json
Labels: S: Untriaged, size/M
