Repository Danil-Alr/SpaceDream_ADT, pull requests merged in 2025-08, with the labels that each got.

#102 Atmos
  Content.Server/SD/CartridgeLoader/Cartridges/AtmoTechCartridgeComponent.cs
  Content.Server/SD/CartridgeLoader/Cartridges/AtmoTechCartridgeSystem.cs
  Content.Shared/CCVar/CCVars.Atmos.cs
  Resources/Locale/ru-RU/SD/aegi.ftl
  Resources/Locale/ru-RU/SD/cartridges.ftl
  Resources/Locale/ru-RU/SD/magboots.ftl
  Resources/Prototypes/ADT/Interface/Radial/RPD.yml
  Resources/Prototypes/ADT/Reagents/gases.yml
  Resources/Prototypes/Catalog/Fills/Lockers/engineer.yml
  Resources/Prototypes/Catalog/Fills/Lockers/heads.yml
  Resources/Prototypes/Catalog/Fills/Lockers/suit_storage.yml
  Resources/Prototypes/Entities/Objects/Devices/pda.yml
  Resources/Prototypes/Entities/Objects/Weapons/Melee/fireaxe.yml
  Resources/Prototypes/Entities/Structures/Piping/Atmospherics/pipes.yml
  Resources/Prototypes/Reagents/gases.yml
  Resources/Prototypes/SD/Entities/Clothing/Shoes/magboots.yml
  Resources/Prototypes/SD/Entities/Mobs/Species/aegi.yml
  Resources/Prototypes/SD/Entities/Objects/Devices/cartridges.yml
  Resources/Textures/ADT/Objects/Tools/rpd.rsi/inhand-left.png
  Resources/Textures/ADT/Objects/Tools/rpd.rsi/inhand-right.png
  Resources/Textures/Objects/Tools/drill.rsi/drill_bolt.png
  Resources/Textures/Objects/Tools/drill.rsi/drill_screw.png
  Resources/Textures/Objects/Tools/drill.rsi/meta.json
  Resources/Textures/Objects/Tools/t-ray.rsi/meta.json
  Resources/Textures/Objects/Tools/t-ray.rsi/tray-off.png
  Resources/Textures/Objects/Tools/t-ray.rsi/tray-on.png
  Resources/Textures/Objects/Weapons/Melee/fireaxe.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Melee/fireaxe.rsi/icon.png
  Resources/Textures/Objects/Weapons/Melee/fireaxe.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/fireaxe.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/fireaxe.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/fireaxe.rsi/wielded-inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/fireaxe.rsi/wielded-inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/equipped-BACKPACK.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/equipped-SUITSTORAGE.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/icon-prot.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/icon.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/inhand-right.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/meta.json
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/wielded-inhand-left.png
  Resources/Textures/Objects/Weapons/Melee/fireaxeflaming.rsi/wielded-inhand-right.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/equipped-FEET.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/icon-on.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/icon.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/inhand-left.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/inhand-right.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/meta.json
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/on-equipped-FEET.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/on-inhand-left.png
  Resources/Textures/SD/Clothing/Shoes/Boots/atmos_magboots.rsi/on-inhand-right.png
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: Localization, ОБСУЖДЕНИЕ

#139 [PORT] [TWEAK] Порт системы пластырей с губов, а также изменение пудры и сульфадиазина
  Content.Server/SD/EntityEffects/EffectConditions/HasComponentOnEquipmentCondition.cs
  Content.Server/SD/MedicalPatch/MedicalPatchComponent.cs
  Content.Server/SD/MedicalPatch/MedicalPatchSystem.cs
  Content.Shared/Sticky/Components/StickyComponent.cs
  Content.Shared/Sticky/Systems/StickySystem.cs
  Resources/Locale/ru-RU/SD/medical-patch.ftl
  Resources/Locale/ru-RU/SD/prototypes/entitites/objects/specific/medical/patches.ftl
  Resources/Locale/ru-RU/SD/prototypes/entitites/objects/specific/medical/sprays.ftl
  Resources/Prototypes/ADT/Catalog/Fills/Items/patchpack.yml
  Resources/Prototypes/ADT/Catalog/VendingMachines/Inventories/civimed.yml
  Resources/Prototypes/ADT/Entities/Objects/Specific/Medical/patchs.yml
  Resources/Prototypes/ADT/Reagents/medicine.yml
  Resources/Prototypes/Catalog/Fills/Items/firstaidkits.yml
  Resources/Prototypes/Catalog/Fills/Lockers/medical.yml
  Resources/Prototypes/Catalog/VendingMachines/Inventories/medical.yml
  Resources/Prototypes/Entities/Structures/Machines/lathe.yml
  Resources/Prototypes/SD/Entities/Objects/Specific/Medical/medical_patch.yml
  Resources/Prototypes/SD/Entities/Objects/Specific/Medical/medical_patch_prefilled.yml
  Resources/Prototypes/SD/Entities/Objects/Specific/Medical/medicalsprays.yml
  Resources/Prototypes/SD/Recipes/Lathes/Packs/medical.yml
  Resources/Prototypes/SD/Recipes/Lathes/medical.yml
  Resources/Prototypes/SD/tags.yml
  Resources/Textures/SD/Objects/Medical/Silverspray.rsi/equipped-BELT.png
  Resources/Textures/SD/Objects/Medical/Silverspray.rsi/icon.png
  Resources/Textures/SD/Objects/Medical/Silverspray.rsi/inhand-left.png
  Resources/Textures/SD/Objects/Medical/Silverspray.rsi/inhand-right.png
  Resources/Textures/SD/Objects/Medical/Silverspray.rsi/meta.json
  Resources/Textures/SD/Objects/Medical/Stypticspray.rsi/equipped-BELT.png
  Resources/Textures/SD/Objects/Medical/Stypticspray.rsi/icon.png
  Resources/Textures/SD/Objects/Medical/Stypticspray.rsi/inhand-left.png
  Resources/Textures/SD/Objects/Medical/Stypticspray.rsi/inhand-right.png
  Resources/Textures/SD/Objects/Medical/Stypticspray.rsi/meta.json
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-1.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-2.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-3.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-4.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-5.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-6.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-7.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-8.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch-9.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatch.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchBorder.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmall-1.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmall-2.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmall-3.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmall-4.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmall-5.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmall.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmallCornerLayer.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/GenericPatchSmallUsed.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/MakeshiftPatch.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/MakeshiftPatchUsed.png
  Resources/Textures/SD/Objects/Medical/medical_patch.rsi/meta.json
Labels: S: Untriaged, size/L, Changes: Sprites, Changes: Localization

#137 Куртка Макишимы
  Resources/Locale/ru-RU/SD/clothing.ftl
  Resources/Prototypes/SD/Entities/Clothing/OuterClothing/Coats/makishima-coat.yml
  Resources/Textures/SD/Clothing/OuterClothing/CustomCoats/bloody-red.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/SD/Clothing/OuterClothing/CustomCoats/bloody-red.rsi/icon.png
  Resources/Textures/SD/Clothing/OuterClothing/CustomCoats/bloody-red.rsi/meta.json
Labels: size/S, Changes: Sprites, Changes: Localization, Changes: No C#

#136 личные вещи реликтеза
  Resources/Locale/ru-RU/SD/personal.ftl
  Resources/Prototypes/SD/Personal/Relictez/relictez_clothing.yml
  Resources/Textures/SD/Personal/Relictez/black_unifrom.rsi/equipped-INNERCLOTHING.png
  Resources/Textures/SD/Personal/Relictez/black_unifrom.rsi/icon.png
  Resources/Textures/SD/Personal/Relictez/black_unifrom.rsi/inhand-left.png
  Resources/Textures/SD/Personal/Relictez/black_unifrom.rsi/inhand-right.png
  Resources/Textures/SD/Personal/Relictez/black_unifrom.rsi/meta.json
  Resources/Textures/SD/Personal/Relictez/cloak_officer.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/SD/Personal/Relictez/cloak_officer.rsi/icon.png
  Resources/Textures/SD/Personal/Relictez/cloak_officer.rsi/inhand-left.png
  Resources/Textures/SD/Personal/Relictez/cloak_officer.rsi/inhand-right.png
  Resources/Textures/SD/Personal/Relictez/cloak_officer.rsi/meta.json
  Resources/Textures/SD/Personal/Relictez/dq_hardsuit_commander.rsi/equipped-OUTERCLOTHING-reptilian.png
  Resources/Textures/SD/Personal/Relictez/dq_hardsuit_commander.rsi/equipped-OUTERCLOTHING.png
  Resources/Textures/SD/Personal/Relictez/dq_hardsuit_commander.rsi/icon.png
  Resources/Textures/SD/Personal/Relictez/dq_hardsuit_commander.rsi/inhand-left.png
  Resources/Textures/SD/Personal/Relictez/dq_hardsuit_commander.rsi/inhand-right.png
  Resources/Textures/SD/Personal/Relictez/dq_hardsuit_commander.rsi/meta.json
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/icon-flash.png
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/icon.png
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/meta.json
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/off-equipped-HELMET.png
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/off-inhand-left.png
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/off-inhand-right.png
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/on-equipped-HELMET.png
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/on-inhand-left.png
  Resources/Textures/SD/Personal/Relictez/dq_helmet_commander.rsi/on-inhand-right.png
Labels: S: Untriaged, Changes: Sprites, Changes: Localization, Changes: No C#
