Repository Danil-Alr/SpaceDream_ADT, pull requests merged in 2025-07, with the labels that each got.

#116 Massmsg
  Content.Server/Administration/Commands/SubtleMessageMassCommand.cs
  Resources/Locale/en-US/administration/commands/subtle-message-mass-command.ftl
Labels: S: Untriaged, size/M, Changes: Localization

#115 Sievert Station
  Resources/Maps/SDMaps/SDShuttles/ERT/Mjolnir.yml
  Resources/Prototypes/Maps/Pools/default.yml
  Resources/Prototypes/SD/Maps/SD_Radiance.yml
  Resources/Prototypes/SD/Maps/SD_Sievert.yml
Labels: size/XL, S: Untriaged, Changes: Map, Changes: No C#

#119 ladders n' keycards
  Content.Server/SD/Cardreader/CardreaderComponent.cs
  Content.Server/SD/Cardreader/CardreaderSystem.cs
  Content.Server/SD/Cardreader/RFIDSystem.cs
  Content.Shared/SD/Cardreader/RFIDComponent.cs
  Content.Shared/SD/_RMC14/Ladder/LadderComponent.cs
  Content.Shared/SD/_RMC14/Ladder/LadderDoAfterEvent.cs
  Content.Shared/SD/_RMC14/Ladder/SharedLadderSystem.cs
  Resources/Audio/SD/Cardreader/entity_cardlock_denied.ogg
  Resources/Audio/SD/Cardreader/entity_cardlock_granted.ogg
  Resources/Locale/ru-RU/SD/rfid-card.ftl
  Resources/Locale/ru-RU/SD/rmc-ladder.ftl
  Resources/Prototypes/SD/Entities/Objects/Specific/Cardreaders/rfid_cards.yml
  Resources/Prototypes/SD/Entities/Structures/cardreader.yml
  Resources/Prototypes/SD/Entities/Structures/rmc_ladder.yml
  Resources/Textures/SD/Entities/Structures/ladder.rsi/ladder00.png
  Resources/Textures/SD/Entities/Structures/ladder.rsi/ladder01.png
  Resources/Textures/SD/Entities/Structures/ladder.rsi/ladder10.png
  Resources/Textures/SD/Entities/Structures/ladder.rsi/ladder11.png
  Resources/Textures/SD/Entities/Structures/ladder.rsi/ladderdown.png
  Resources/Textures/SD/Entities/Structures/ladder.rsi/ladderup.png
  Resources/Textures/SD/Entities/Structures/ladder.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/silver.png
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: Audio, Changes: Localization

#121 Cardreader sprites
  Resources/Locale/ru-RU/SD/rfid-card.ftl
  Resources/Prototypes/SD/Entities/Objects/Specific/Cardreaders/rfid_cards.yml
  Resources/Prototypes/SD/Entities/Structures/cardreader.yml
  Resources/Textures/SD/Entities/Structures/cardreader.rsi/dead.png
  Resources/Textures/SD/Entities/Structures/cardreader.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/cube.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/five.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/four.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/icon.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/lambda.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/line.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/magnetic_line.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/meta.json
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/one.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/psi.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/sigma.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/silver.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/six.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/square.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/three.png
  Resources/Textures/SD/Objects/Specific/Cardreader/Cards/card.rsi/two.png
Labels: S: Untriaged, size/M, Changes: Sprites, Changes: Localization, Changes: No C#

#122 Кейпады
  Content.Client/_SD/Keypad/UI/KeypadBoundUserInterface.cs
  Content.Client/_SD/Keypad/UI/KeypadMenu.xaml
  Content.Client/_SD/Keypad/UI/KeypadMenu.xaml.cs
  Content.Server/SD/Keypad/KeypadComponent.cs
  Content.Server/SD/Keypad/KeypadSystem.cs
  Content.Shared/_SD/Keypad/KeypadStates.cs
  Content.Shared/_SD/Keypad/SharedKeypad.cs
  Resources/Locale/ru-RU/SD/keypad.ftl
  Resources/Prototypes/SD/Entities/Objects/Devices/keypad.yml
Labels: size/M, Changes: UI, Changes: Localization
